// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: querry.sql

package url

import (
	"context"
	"database/sql"
)

const createUrl = `-- name: CreateUrl :exec
INSERT INTO url (
	shortURL,
	longURL,
	created
)
VALUES (
	?,
	?,
	?
)
`

type CreateUrlParams struct {
	Shorturl string
	Longurl  sql.NullString
	Created  sql.NullTime
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) error {
	_, err := q.db.ExecContext(ctx, createUrl, arg.Shorturl, arg.Longurl, arg.Created)
	return err
}

const getUrl = `-- name: GetUrl :one
SELECT shortURL, longURL, created
FROM url
WHERE shortURL = ?
`

func (q *Queries) GetUrl(ctx context.Context, shorturl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrl, shorturl)
	var i Url
	err := row.Scan(&i.Shorturl, &i.Longurl, &i.Created)
	return i, err
}
